# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('amount', models.FloatField(default=0, null=True)),
                ('unit', models.CharField(blank=True, choices=[('ml', 'ml'), ('g', 'g'), ('kg', 'kg'), ('cup', 'cup'), ('None', '')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.IntegerField(blank=True, default=0)),
                ('favorite', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('notes', models.TextField(blank=True, null=True)),
                ('recipe_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='RecipeManager.Recipe')),
            ],
            options={
                'ordering': ['-version_num'],
            },
        ),
        migrations.AddField(
            model_name='method',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='RecipeManager.Version'),
        ),
        migrations.AddField(
            model_name='itemlist',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='RecipeManager.Version'),
        ),
    ]
