# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='recipe_name',
            new_name='recipe',
        ),
    ]
