# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeManager', '0003_auto_20170429_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='version',
        ),
        migrations.DeleteModel(
            name='Method',
        ),
    ]
